# ansible-playbook ./ansible/playbook.yml -i ./ansible/inventory -vv
- hosts: localhost
  vars:
    docker_image: zhenik/calculator
  connection: local
  tasks:
    - name: Filter docker for specific container
      shell: docker ps -a -q --filter ancestor={{docker_image}}
      register: container_id

    - name: Print container id
      command: echo {{container_id.stdout}}

    - name: Get all containers
      command: docker ps -a -q
      register: containers

    - name: Print containers
      command: echo {{containers.stdout}}

    - name: Stop & Remove containers
      command: docker stop {{containers.stdout}}
      when: containers.stdout != ""

#    - name: Stop container if exists
#      command: docker stop {{container_id.stdout}}
#      when: container_id.stdout != ""

#    - name: Remove container if exists
#      command: docker rm {{container_id.stdout}}
#      when: container_id.stdout != ""

    - name: Find dangling images
      command: docker images -f dangling=true -q
      register: dangling_images

    - name: Remove dangling images
      command: docker rmi -f {{dangling_images.stdout}}
      when: dangling_images.stdout != ""

    - name: Remove image
      shell: docker rmi {{docker_image}}

    - name: Pull new image
      shell: docker pull {{docker_image}}

    - name: Up new container
      shell: docker run --rm -d -p8082:8080 {{docker_image}}

    - name: Wait 60 seconds
      pause: seconds=60

    - name: Health check
      uri:
        url: http://localhost:8082/health-check
        method: GET
        status_code: 200
        timeout: 30