# ansible-playbook ./ansible/playbook.yml -i ./ansible/inventory -vv
- hosts: localhost
  vars:
    docker_image: zhenik/calculator
  connection: local
  tasks:
    - name: Filter docker for specific container
      shell: docker ps -a -q --filter ancestor={{docker_image}}
      register: container_id

    - name: Print container id
      shell: echo {{container_id.stdout}}

    - name: Stop container
      shell: docker stop {{container_id.stdout}}

    - name: Remove container
      shell: docker rm {{container_id.stdout}}

    - name: Remove image
      shell: docker rmi {{docker_image}}

    - name: Pull new image
      shell: docker pull {{docker_image}}

    - name: Up new container
      shell: docker run -d -p8081:8080 {{docker_image}}

    - name: Wait 300 seconds, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Health check
      uri:
        url: http://localhost:8081/health-check
        method: GET
        status_code: 200
        timeout: 30